// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARoxW05cQG_a_gvfnsXsPcLdsVViB1UCw',
    appId: '1:128786465115:web:13f1882e4c205fe60e5a7e',
    messagingSenderId: '128786465115',
    projectId: 'devpaul-ed0bb',
    authDomain: 'devpaul-ed0bb.firebaseapp.com',
    storageBucket: 'devpaul-ed0bb.appspot.com',
    measurementId: 'G-V9FD2JWCJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs8B30UQL_Leqi0eR9CnVH6vFZObc1aC8',
    appId: '1:128786465115:android:7ad5590dc0d51e120e5a7e',
    messagingSenderId: '128786465115',
    projectId: 'devpaul-ed0bb',
    storageBucket: 'devpaul-ed0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa02Sn644zFJKXqwJi_emIlzJL4HkNPUQ',
    appId: '1:128786465115:ios:2658c012481ce9e40e5a7e',
    messagingSenderId: '128786465115',
    projectId: 'devpaul-ed0bb',
    storageBucket: 'devpaul-ed0bb.appspot.com',
    iosClientId: '128786465115-k1taigb713lauorus7msg94bgpfinala.apps.googleusercontent.com',
    iosBundleId: 'co.devpaul.devpaulCo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa02Sn644zFJKXqwJi_emIlzJL4HkNPUQ',
    appId: '1:128786465115:ios:2658c012481ce9e40e5a7e',
    messagingSenderId: '128786465115',
    projectId: 'devpaul-ed0bb',
    storageBucket: 'devpaul-ed0bb.appspot.com',
    iosClientId: '128786465115-k1taigb713lauorus7msg94bgpfinala.apps.googleusercontent.com',
    iosBundleId: 'co.devpaul.devpaulCo',
  );
}
